apiVersion: v1
kind: Service
metadata:
  name: $name 
  labels: 
    app: pansecurityadapter
    app.kubernetes.io/name: "$name"
    app.kubernetes.io/component: "$name" 
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 9693 
    targetPort: 9693 
  selector:
    app: pansecurityadapter
    app.kubernetes.io/name: "$name"
    app.kubernetes.io/component:  "$name"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $name 
  labels:
    app: pansecurityadapter
    app.kubernetes.io/name: "$name"
    app.kubernetes.io/component:  "$name"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pansecurityadapter
      app.kubernetes.io/name: "$name"
      app.kubernetes.io/component:  "$name"
  template:
    metadata:
      labels: 
        app: pansecurityadapter
        app.kubernetes.io/name: "$name"
        app.kubernetes.io/component: "$name" 
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: $name 
        image: $securityAdapterImageName 
        imagePullPolicy: Always
        ports:
        - containerPort: 9693 
        volumeMounts:
        - name: transient-storage
          mountPath: /volume
        env:
        - name: SECURITY_POLICY_API_ENDPOINT
          value: "http://$securityPolicyApiEndpoint:$securityPolicyApiPort" 
      volumes:
      - name: transient-storage
        emptyDir: {}
